engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - BUG
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
- node_modules/
- server/test/
- templates