/**
 * action types
 */
export default {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_USER: 'LOGOUT_USER',
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  CREATE_GROUP: 'CREATE_GROUP',
  ADD_MEMBER: 'ADD_MEMBER',
  MEMBER_CLICKED: 'MEMBER_CLICKED',
  DELETE_MEMBER: 'DELETE_MEMBER',
  DELETE_GROUP: 'DELETE_GROUP',
  SEND_MESSAGE: 'SEND_MESSAGE',
  SEND_ERROR: 'SEND_ERROR',
  SEND_PENDING: 'SEND_PENDING',
  VISIBILTY_FILTERS: {
    SHOW_ALL: 'SHOW_ALL',
    SHOW_READ: 'SHOW_READ',
    SHOW_UNREAD: 'SHOW_UNREAD',
    SHOW_CRITICAL: 'SHOW_CRITICAL',
    SHOW_URGENT: 'SHOW_URGENT',
    SHOW_NORMAL: 'SHOW_NORMAL'
  },
  SELECTION_FILTERS: {
    MARK_AS_READ: 'MARK_AS_READ',
    MARK_AS_UNREAD: 'MARK_AS_UNREAD',
    SHOW_USER_DETAILS: 'SHOW_USER_DETAILS',
  }
};
